Valtech_Form_App/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Valtech_Form_BusinessLogic.Data;
using Valtech_Form_BusinessLogic.Managers;
using Valtech_Form_BusinessLogic.Models;

namespace Valtech_Form_App.Controllers
{
    public class FormController : Controller
    {
        private FormEntryManager _formEntryManager;

        public FormController(FormDbContext context)
        {
            _formEntryManager = new FormEntryManager(context);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Submit(FormModel model)
        {
            // Return to form if modelstate is not valid
            if (!ModelState.IsValid)
            {
                return View("/Pages/Modules/FormView.cshtml", model);
            }

            try
            {
                _formEntryManager.Create(model);
            }
            catch (InvalidOperationException e)
            {
                TempData["ErrorMessage"] = e.Message;
                return RedirectToAction("Index", "Index");
            }

            // Show a message that the creation of a new entry was succesful
            TempData["Message"] = "Nieuwe entry succesvol aangemaakt.";

            // Return to home screen
            return RedirectToAction("Index", "Index");
        }
    }
}

Valtech_Form_App/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Valtech_Form_BusinessLogic.Data;
using Valtech_Form_BusinessLogic.Managers;
using Valtech_Form_BusinessLogic.Models;

namespace Valtech_Form_App.Controllers
{
    public class IndexController : Controller
    {
        /// <summary>
        /// Handler for database actions
        /// </summary>
        private FormEntryManager _formEntryManager;

        public IndexController(FormDbContext context)
        {
            _formEntryManager = new FormEntryManager(context);
        }

        public IActionResult Index()
        {
            // Get all the entries saved in the database
            IndexModel model = new IndexModel();
            model.FormEntries = _formEntryManager.GetAllEntries();

            return View("/Pages/Index.cshtml", model);
        }

        public IActionResult Delete(int id)
        {
            // Delete the entry from the database
            _formEntryManager.Delete(id);

            // Show a message that the delete was succesful
            TempData["Message"] = $"Entry met id {id} was succesvol verwijderd.";
            
            return RedirectToAction("Index");
        }
    }
}

Valtech_Form_App/Pages/Index.cshtml
@using Valtech_Form_BusinessLogic.Models
@model IndexModel
@{
    if (ViewData != null)
    {
        ViewData["Title"] = "Home";
    }
}

@if (TempData["Message"] != null && !string.IsNullOrEmpty(TempData["Message"].ToString())) {
    <span class="text-success">@TempData["Message"]</span>
}

@await Html.PartialAsync("/Pages/Modules/FormView.cshtml", new FormModel())
@await Html.PartialAsync("/Pages/Modules/EntriesView.cshtml", Model.FormEntries)

Valtech_Form_App/Pages/Modules/EntriesView.cshtml
@model IEnumerable<FormModel>
@using Valtech_Form_BusinessLogic.Models

<div class="mod-entries-view">
    <h2>Formulier entries (@Model.Count()/10)</h2>

    @foreach (FormModel formEntry in Model)
    {
        <div>
            <h3>Entry (Id @formEntry.Id) - @Html.ActionLink("Delete", "Delete", new { id = formEntry.Id})</h3>
            <table>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().FirstName)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.FirstName) ? "<em>Niet ingevuld</em>" : formEntry.FirstName))</td>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().Surname)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.Surname) ? "<em>Niet ingevuld</em>" : formEntry.Surname))</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().Email)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.Email) ? "<em>Niet ingevuld</em>" : formEntry.Email))</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().Address)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.Address) ? "<em>Niet ingevuld</em>" : formEntry.Address))</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().ZipCode)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.ZipCode) ? "<em>Niet ingevuld</em>" : formEntry.ZipCode))</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(model => model.FirstOrDefault().PhoneNumber)</th>
                    <td>@(Html.Raw(string.IsNullOrEmpty(formEntry.PhoneNumber) ? "<em>Niet ingevuld</em>" : formEntry.PhoneNumber))</td>
                </tr>
                <tr>
                    <th>Akkoord met de algemene voorwaarden</th>
                    <td>@(formEntry.AgreedToTermsAndConditions ? "Ja" : "Nee")</td>
                </tr>
            </table>
        </div>
    }
</div>

Valtech_Form_App/Pages/Modules/FormView.cshtml
@model Valtech_Form_BusinessLogic.Models.FormModel
<div class="mod-form-view">
    <h2>Nieuwe entry aanmaken</h2>

    @if(TempData["ErrorMessage"] != null && !string.IsNullOrEmpty(TempData["ErrorMessage"].ToString()))
    {
        <span class="text-danger">@TempData["ErrorMessage"]</span>
    }

    @using (Html.BeginForm("Submit", "Form", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control"})
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname) *
            @Html.TextBoxFor(model => model.Surname, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email) *
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address)
            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode)
            @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgreedToTermsAndConditions) *
            @Html.CheckBoxFor(model => model.AgreedToTermsAndConditions, new { @class = "form-check-input" })
            <br />
            @Html.ValidationMessageFor(model => model.AgreedToTermsAndConditions, "", new { @class = "text-danger" })
        </div>

        @Html.AntiForgeryToken()

        <input type="submit" class="btn btn-primary" value="Verzenden" title="Verzenden" alt="Verzend het formulier" />
    }
</div>

Valtech_Form_App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        <header>
            <h1>@ViewData["Title"]</h1>
        </header>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Valtech_Form_App</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>